# fly.toml app configuration file generated for dial-a-poem on 2024-08-01T02:07:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dial-a-poem'
primary_region = 'iad'

[build]

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 2
